### ISSUE TITLE
Scheduler & Scraper Not Working

### ISSUE THREAD

**Issue by semihada** [furkankose/bilkent-scheduler#2]
The spring offerings are announced. Though the website did not add the Spring courses. I locally built the website it's working fine but the scraper. Requests sent by the Requee library has always return failed status. I suspect that might be the case. Below snippet contains the first function I encountered this problem.
https://github.com/furkankose/bilkent-scheduler/blob/81398e4a614dc3d5a0de33da3e1e9ba921237fc4/scraper/services/bilkent.service.js#L8C1-L20C1

**Comment by furkankose** [comment]
Hi @semihada,

I’ve reviewed and tested the client and scraper, and both appear to be working fine. Upon further investigation, I realized that the scraper's method for detecting the new semester was coded to start fetching data one month before the "Departments finalize schedules, quotas, and elective pools" date in the academic calendar.

Because of this, the scraper hadn't started fetching the Spring semester's data yet. I’ve updated this one-month period to 40 days, so the system should have the updated data by tomorrow. Please check it again tomorrow and let me know if the issue still persists

**Comment by semihada** [comment]
Thanks @furkankose, now it is working. Eline saglik!
